openapi: 3.2.0
info:
  title: Audatex.APIGateway Repairers API
  termsOfService: https://www.solera.com/legal/
  contact:
    name: Solera Development Team
    url: https://docs.microsoft.com/en-us/aspnet/core/tutorials/getting-started-with-swashbuckle?view=aspnetcore-2.2&tabs=visual-studio
    email: development@solera.com
  license:
    name: License
    url: https://www.solera.com/legal/
  version: V1
servers:
- url: /APIGateway
security:
- Bearer: []
- Bearer: []
tags:
- name: Repairers
paths:
  /api/v1/Repairers/search:
    get:
      tags:
      - Repairers
      summary: Search repairers by name
      description: This endpoint performs a wildcard search on Repairer name and aliases.
      parameters:
      - name: country
        in: query
        required: true
        schema:
          $ref: '#/components/schemas/Country'
      - name: name
        in: query
        required: true
        schema:
          minLength: 2
          type: string
      - name: pageSize
        in: query
        schema:
          type: integer
          format: int32
      - name: page
        in: query
        schema:
          type: integer
          format: int32
      responses:
        '200':
          description: Returns list of entities
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/RepairerRespVM'
        '400':
          description: Returns an error if the request fails validation
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ProblemDetails'
        '500':
          description: Sorry, an unexpected error has occurred
        '401':
          description: Returns an error if the user is not authorised
      operationId: getApiV1RepairersSearch
      x-operation-id-source: derived
components:
  schemas:
    ProblemDetails:
      type: object
      properties:
        type:
          type:
          - string
          - 'null'
        title:
          type:
          - string
          - 'null'
        status:
          type:
          - integer
          - 'null'
          format: int32
        detail:
          type:
          - string
          - 'null'
        instance:
          type:
          - string
          - 'null'
      additionalProperties: {}
    Country:
      enum:
      - UK
      - ZA
      - US
      - CA
      - FR
      - IE
      - RO
      - PL
      - CH
      - AD
      - AR
      - AU
      - AT
      - AZ
      - BH
      - BY
      - BE
      - BA
      - BW
      - BR
      - BG
      - CL
      - CN
      - CO
      - CR
      - HR
      - CZ
      - DK
      - DO
      - EC
      - SV
      - EE
      - FI
      - GF
      - DE
      - GR
      - GP
      - GT
      - HN
      - HU
      - IS
      - IN
      - ID
      - IL
      - IT
      - JP
      - KR
      - KW
      - LV
      - LT
      - LU
      - MY
      - MT
      - MQ
      - MX
      - MD
      - ME
      - MA
      - NA
      - NL
      - NC
      - NZ
      - NI
      - 'NO'
      - OM
      - PA
      - PE
      - PT
      - PR
      - MK
      - RU
      - RE
      - SA
      - RS
      - SG
      - SK
      - SI
      - ES
      - SE
      - TW
      - TR
      - UA
      - AE
      - GB
      - VE
      type: string
    RepairerRespVM:
      type: object
      properties:
        id:
          type: string
          format: uuid
        name:
          type:
          - string
          - 'null'
        countryCode:
          type:
          - string
          - 'null'
        address:
          $ref: '#/components/schemas/AddressResponseVM'
        aliases:
          type:
          - array
          - 'null'
          items:
            type: string
      additionalProperties: false
    AddressResponseVM:
      type: object
      properties:
        line1:
          type:
          - string
          - 'null'
          description: Street address / P.O. Box
        line2:
          type:
          - string
          - 'null'
          description: Additional address data
        line3:
          type:
          - string
          - 'null'
          description: Locality
        line4:
          type:
          - string
          - 'null'
          description: City / Postal Town
        line5:
          type:
          - string
          - 'null'
          description: County / Province / State
        line6:
          type:
          - string
          - 'null'
          description: Postal Code / ZIP
        country:
          type:
          - string
          - 'null'
        latitude:
          type:
          - number
          - 'null'
          format: double
        longitude:
          type:
          - number
          - 'null'
          format: double
      additionalProperties: false
  securitySchemes:
    Bearer:
      type: apiKey
      description: "JWT Authorization header using the Bearer scheme. \n\n Enter 'Bearer' [space] and then your token in the text input below.\n\nExample: \"Bearer 12345abcdef\""
      name: Authorization
      in: header
